### ISSUE TITLE
Matek F411RX - Motors don't spin on setup (running JESC 2.2)

### ISSUE THREAD

**Issue by Hellfire82** [FlightOne/FalcoX-Issue-Tracker#11]
10.0.6.2807 Alpha

Matekf411

Tinyhawk S which uses the Matek F411RX board, however I have installed an FrSky XM+ so am not using the SPI receiver.

FalcoX installs correctly & the receiver works, however when I reach the part of the setup wizard which asks if the motors are turning, none of them move even when the idle is set to 100%. Even when I bypass this by selecting yes, none of the motors turn in the next wizard to allow me to identify which of the 4 motors is turning. After bypassing this wizard by guessing which motors should be turning & power cycling, there is a constant flashing red light on the board.

In the wizard I selected BLHeli_S, however I am running JESC V 2.2 to take advantage of the 48kHz benefits.

**Comment by PGIII** [comment]
Im pretty sure the MatekF411Rx is a different target completely so probably part of the issue

**Comment by Hellfire82** [comment]
It is a different target, but the RX refers to the built in SPI receiver (which I'm not using).
You'll know more than me but I'm presuming my use of JESC instead of BlHeli_S may be the issue?

If this can't be rectified I may have to get a refund & go back to Betaflight :(

**Comment by Hellfire82** [comment]
Flashed Matekf411 Version: 10.0.6.2818 Alpha and motors 2 and 3 now spin during the setup wizard, but motors 1 and 4 don't spin at all.

Flashed the 4in1 ESC back to BlHeli_S 16.7 and nothing changed, so I've reverted back to JESC 2.2.

Looks like this issue is fixable since 2 motors now spin due to what you released in Patch 3 for Beta 6 :)

**Comment by PGIII** [comment]
[FLX_MATEKF411RX_10.0.6.2860.zip](https://github.com/FlightOne/FalcoX-Issue-Tracker/files/4289616/FLX_MATEKF411RX_10.0.6.2860.zip)
Try that firmware and see if it works, (Make sure to unzip it before you flash :) )

**Comment by Hellfire82** [comment]
Getting closer!
All motors spin and I'm able to complete the setup wizard. However when I power cycle after the last step of setting up angle mode, the wizard starts again. It's as if it doesn't save.
Many thanks for going out of your way to find a solution. I know it's not an official supported target and you could've quite easily said no.
I'm FlightOne for life!

**Comment by PGIII** [comment]
[FLX_MATEKF411RX_10.0.6.2863.zip](https://github.com/FlightOne/FalcoX-Issue-Tracker/files/4289867/FLX_MATEKF411RX_10.0.6.2863.zip)
This should fix the saving let me know

**Comment by Hellfire82** [comment]
It's still not saving.
Flashed with both the old and the latest configurator (2.0.1) on three occasions to make sure.

**Comment by Enlightx** [comment]
just tried it also getting the same run the setup wizard. motors all spin perfect... but then after you power cycle wizard starts again

**Comment by Hellfire82** [comment]
Latest alpha 10.0.6.2999 has solved the saving issue and all motors spin.

**Comment by Enlightx** [comment]
just tested this and i still only have 2 motors spinning on tinyhawk2 using stock ESC not jesc ?

**Comment by gretel** [comment]
@PGIII does this support the builtin `spi` receiver?
